package com.labs.three.effect;

public enum EffectType {
    ON_ATTACK_TO_DEFENDER,
    ON_ATTACK_TO_ATTACKER,
    ON_ATTACK_TO_ATTACK_TEAM,
    ON_ATTACK_TO_DEFEND_TEAM,
    ON_ATTACK_TO_ALL,
    ON_DEFEND_TO_DEFENDER,
    ON_DEFEND_TO_ATTACKER,
    ON_DEFEND_TO_ATTACK_TEAM,
    ON_DEFEND_TO_DEFEND_TEAM,
    ON_DEFEND_TO_ALL,
    ON_DEATH
}
